# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b7dcd0cdb07b7f50921cc5180b4d0cd7feb01b013b1f06ac25d29b7183e9db337acd1c59631b1579bcfd764c5ccd3e379d952e10bf67d69efd601d096ad5d3

test:
  secret_key_base: f753caaff803e870891bcb2f04ddfdb5c0714f8e38c9e05f5dd240b0994f09dba5fad280a029e8bfd858b842652c486ad5fc567c8350e6bf3d13b9f02f8ad94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
